export const instrumentList = [
  { value: 'FLAUTA', label: 'Flauta' },
  { value: 'OBOE', label: 'Oboé' },
  { value: 'CLARINETE', label: 'Clarinete' },
  { value: 'FAGOTE', label: 'Fagote' },
  { value: 'TROMPA', label: 'Trompa' },
  { value: 'TROMPETE', label: 'Trompete' },
  { value: 'TROMBONE', label: 'Trombone' },
  { value: 'TUBA', label: 'Tuba' },
  { value: 'VIOLINO', label: 'Violino' },
  { value: 'VIOLA', label: 'Viola' },
  { value: 'VIOLONCELO', label: 'Violoncelo' },
  { value: 'CONTRABAIXO', label: 'Contrabaixo' },
  { value: 'HARPA', label: 'Harpa' },
  { value: 'PIANO', label: 'Piano' },
  { value: 'TIMPANOS', label: 'Tímpanos' },
  { value: 'PERCUSSAO', label: 'Percussão' },
  { value: 'SOPRANO', label: 'Soprano' },
  { value: 'CONTRALTO', label: 'Contralto' },
  { value: 'TENOR', label: 'Tenor' },
  { value: 'BAIXO', label: 'Baixo' },
  { value: 'PARTITURA', label: 'Partitura' },
  { value: 'PARTITURA_COMPLETA', label: 'Partitura Completa' },
  { value: 'OUTRO', label: 'Outro' },
]; 