export const instrumentList = [
  { value: 'FLAUTIM', label: 'Flautim' },
  { value: 'PICCOLO', label: 'Piccolo' },
  { value: 'FLAUTA', label: 'Flauta' },
  { value: 'FLAUTA_1', label: 'Flauta 1' },
  { value: 'FLAUTA_2', label: 'Flauta 2' },
  { value: 'FLAUTA_3', label: 'Flauta 3' },
  { value: 'OBOE', label: 'Oboé' },
  { value: 'OBOE_1', label: 'Oboé 1' },
  { value: 'OBOE_2', label: 'Oboé 2' },
  { value: 'OBOE_3', label: 'Oboé 3' },
  { value: 'CORNE_INGLES', label: 'Corne inglês' },
  { value: 'CLARINETE', label: 'Clarinete' },
  { value: 'CLARINETE_1', label: 'Clarinete 1' },
  { value: 'CLARINETE_2', label: 'Clarinete 2' },
  { value: 'CLARINETE_3', label: 'Clarinete 3' },
  { value: 'CLARONE', label: 'Clarone' },
  { value: 'CLARINETE_BAIXO', label: 'Clarinete baixo' },
  { value: 'FAGOTE', label: 'Fagote' },
  { value: 'FAGOTE_1', label: 'Fagote 1' },
  { value: 'FAGOTE_2', label: 'Fagote 2' },
  { value: 'FAGOTE_3', label: 'Fagote 3' },
  { value: 'CONTRAFAGOTE', label: 'Contrafagote' },
  { value: 'TROMPA', label: 'Trompa' },
  { value: 'TROMPA_1', label: 'Trompa 1' },
  { value: 'TROMPA_2', label: 'Trompa 2' },
  { value: 'TROMPA_3', label: 'Trompa 3' },
  { value: 'TROMPA_4', label: 'Trompa 4' },
  { value: 'TROMPA_5', label: 'Trompa 5' },
  { value: 'TROMPETE', label: 'Trompete' },
  { value: 'TROMPETE_1', label: 'Trompete 1' },
  { value: 'TROMPETE_2', label: 'Trompete 2' },
  { value: 'TROMPETE_3', label: 'Trompete 3' },
  { value: 'TROMPETE_4', label: 'Trompete 4' },
  { value: 'TROMBONE', label: 'Trombone' },
  { value: 'TROMBONE_ALTO', label: 'Trombone alto' },
  { value: 'TROMBONE_TENOR', label: 'Trombone tenor' },
  { value: 'TROMBONE_BAIXO', label: 'Trombone baixo' },
  { value: 'TROMBONE_1', label: 'Trombone 1' },
  { value: 'TROMBONE_2', label: 'Trombone 2' },
  { value: 'TROMBONE_3', label: 'Trombone 3' },
  { value: 'TROMBONE_4', label: 'Trombone 4' },
  { value: 'TUBA', label: 'Tuba' },
  { value: 'TIMPANOS', label: 'Tímpanos' },
  { value: 'TIMPANOS_ALT', label: 'Timpanos' },
  { value: 'PERCUSSAO', label: 'Percussão' },
  { value: 'PERCUSSAO_1', label: 'Percussão 1' },
  { value: 'PERCUSSAO_2', label: 'Percussão 2' },
  { value: 'PERCUSSAO_3', label: 'Percussão 3' },
  { value: 'PERCUSSAO_4', label: 'Percussão 4' },
  { value: 'PERCUSSAO_5', label: 'Percussão 5' },
  { value: 'PERCUSSAO_6', label: 'Percussão 6' },
  { value: 'BOMBO', label: 'Bombo' },
  { value: 'CAIXA', label: 'Caixa' },
  { value: 'BOMBO_CAIXA', label: 'Bombo e caixa' },
  { value: 'TRIANGLE', label: 'Triangle' },
  { value: 'CONGAS', label: 'Congas' },
  { value: 'ATABAQUES', label: 'Atabaques' },
  { value: 'CAXIXI', label: 'Caxixi' },
  { value: 'XILOFONE', label: 'Xilofone' },
  { value: 'XILOPHONE', label: 'Xilophone' },
  { value: 'VIBRAFONE', label: 'Vibrafone' },
  { value: 'VIBRAPHONE', label: 'Vibraphone' },
  { value: 'PIANO', label: 'Piano' },
  { value: 'PIANO_FORTE', label: 'Piano forte' },
  { value: 'HARPA', label: 'Harpa' },
  { value: 'CORO', label: 'Coro' },
  { value: 'VOZ', label: 'Voz' },
  { value: 'VIOLINO_1', label: 'Violino 1' },
  { value: 'VIOLINO_2', label: 'Violino 2' },
  { value: 'VIOLA', label: 'Viola' },
  { value: 'VIOLONCELO', label: 'Violoncelo' },
  { value: 'CONTRABAIXO', label: 'Contrabaixo' },
  { value: 'BAIXO_ELETRICO', label: 'Baixo elétrico' },
]; 